### PR TITLE
Feat/cs/fix edited multipart

### LINKED ISSUE #277: Multipart messages where one attachment was unsent make the entire message display as unsent
The bugged view looks like this:

image

In theory, it should look like this:

image

The content still exists in the body like:

`text: Some("From arbitrary byte stream:\r￼To native Rust data structures:\r")`

And we still parse the message parts correctly:

`[Text("From arbitrary byte stream:"), Attachment, Text("To native Rust data structures:")]`

However, there is no `ec`:

https://github.com/ReagentX/imessage-exporter/blob/bf8b4455bb934477f42e5dac089a4532c750e5ea/imessage-database/src/message_types/edited.rs#L63-L65

Which makes the `message_summary_info` look like a normal unsent message:

https://github.com/ReagentX/imessage-exporter/blob/bf8b4455bb934477f42e5dac089a4532c750e5ea/imessage-database/src/message_types/edited.rs#L109-L112

This is technically true, because the last part of the message was unsent, but the other 3 parts are still there. Possibly we need to be smarter about detecting when a message was actually unsent; edited messages also contain a `amc` key (representing the party that edited the message) that unsent messages do not. It is possible we may just need to validate `amc` instead of `ec`.

Further, it is likely, both of these are not needed:

https://github.com/ReagentX/imessage-exporter/blob/bf8b4455bb934477f42e5dac089a4532c750e5ea/imessage-exporter/src/exporters/html.rs#L303-L315

https://github.com/ReagentX/imessage-exporter/blob/bf8b4455bb934477f42e5dac089a4532c750e5ea/imessage-exporter/src/exporters/html.rs#L319-L321

### LINKED ISSUE #311: `Message::date_edited()` does not get the edited date
https://github.com/ReagentX/imessage-exporter/blob/83e1f82a0e67cba4572f40ab55fec0953263af98/imessage-database/src/tables/messages/message.rs#L461-L466

### PR DESCRIPTION
**Pull request by ReagentX**
- Refactor `EditedMessage` design to support multi-part messages
  - Fix #277 
  - Use new `typedstream` deserializer for edited message body data
- Support interior `Mention` contact reference data
- Rename `BubbleType` to `BubbleComponent`
- Fix #311

### CODE REVIEW

File: imessage-database/src/message_types/edited.rs [hunk 1]
```diff
@@ -9,122 +11,205 @@ use crate::{
...
-            let timestamp = extract_int_key(message_data, "d")? * TIMESTAMP_FACTOR;
-
-            let raw_streamtyped = extract_bytes_key(message_data, "t")?;
-            let text =
-                parse(raw_streamtyped.to_vec()).map_err(PlistParseError::StreamTypedError)?;
-
-            let guid = message_data.get("bcg").and_then(|item| item.as_string());
+            .for_each(|_| edited.parts.push(EditedMessagePart::default()));
+
+        let maybe_edited_message_events = extract_dictionary(plist_root, "ec").ok();
```
Comment (ReagentX) [inline imessage-database/src/message_types/edited.rs]: Inline this

File: imessage-database/src/message_types/edited.rs [hunk 2]
```diff
@@ -9,122 +11,205 @@ use crate::{
...
+        let maybe_unsent_message_indexes = extract_array_key(plist_root, "rp").ok();
```
Comment (ReagentX) [inline imessage-database/src/message_types/edited.rs]: Inline this

File: imessage-database/src/message_types/edited.rs [hunk 3]
```diff
@@ -9,122 +11,205 @@ use crate::{
...
+
+        if let Some(edited_message_events) = maybe_edited_message_events {
+            for (idx, (key, events)) in edited_message_events.iter().enumerate() {
+                let events = events
+                    .as_array()
+                    .ok_or_else(|| PlistParseError::InvalidTypeIndex(idx, "array".to_string()))?;
+                let parsed_key = key.parse::<usize>().unwrap();
```
Comment (ReagentX) [inline imessage-database/src/message_types/edited.rs]: Handle error

File: imessage-database/src/message_types/edited.rs [hunk 4]
```diff
@@ -9,122 +11,205 @@ use crate::{
...
+    /// Gets the edited message data for the given message part index
+    pub fn is_unedited_at(&self, index: usize) -> bool {
+        match self.parts.get(index) {
+            Some(part) => matches!(part.status, EditStatus::Original),
+            None => false,
+        }
     }
 
-    /// Gets the number of items in the edit history
+    /// Gets the number of parts that were edited
```
Comment (ReagentX) [inline imessage-database/src/message_types/edited.rs]: The number of parts of any edit status
